### ISSUE TITLE
Suggestion: add a way to sync pic/photo to contact

### ISSUE THREAD

**Issue by ChristopheVersieux** [c99koder/AndroidSyncProviderDemo#1]
Hello,

You made an awesome work with this project.
Unfortunately, I really would like to add a picture to Elmer Fudd, but I have totally no idea on how to do that.

Is that easily feasible?

Thank a lot for your help and sharing your work!

**Comment by ChristopheVersieux** [comment]
Just answering my request..

Bitmap bmImage = BitmapFactory.decodeFile(Environment
                .getExternalStorageDirectory().getAbsolutePath()
                + DIRPATH+"/pics/"
                + trigram.toUpperCase() + ".JPG");
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        if (bmImage != null)
            bmImage.compress(Bitmap.CompressFormat.JPEG, 80, baos);
        else
            Log.i("","NOPIC "+name);
        byte[] b = baos.toByteArray();
        builder = ContentProviderOperation
                .newInsert(ContactsContract.Data.CONTENT_URI);
        builder.withValueBackReference(ContactsContract.Data.RAW_CONTACT_ID, 0);
        builder.withValue(ContactsContract.Data.MIMETYPE,
                ContactsContract.CommonDataKinds.Photo.CONTENT_ITEM_TYPE);
        builder.withValue(ContactsContract.CommonDataKinds.Photo.DATA15, b);
        operationList.add(builder.build());

**Comment by c99koder** [comment]
I've added an image to the sample contact for future reference

**Comment by c99koder** [comment]
btw, in reference to the code you pasted, you can just read the file's bytes directly into an array, instead of decoding and then re-encoding the jpeg.  I used BitmapFactory in my own sample just because I was referencing a Drawable instead of an image file.
